#
# embedXcode
# ----------------------------------
# Embedded Computing on Xcode
#
# Copyright © Rei VILO, 2010-2016
# http://embedxcode.weebly.com
# All rights reserved
#
# Last update: Feb 27, 2016 release 4.3.5
#

# ----------------------------------
# DO NOT EDIT THIS FILE.
# ----------------------------------

EMBEDXCODE_RELEASE      = 4.3.5
EMBEDXCODE_DATE         = Feb 27, 2016
EMBEDXCODE_MESSAGE      = Updated boards for Arduino.CC IDE

# ~
EMBEDXCODE_EDITION      = embedXcode for Wiring / Arduino
EMBEDXCODE_REFERENCE    = embedXcode
EMBEDXCODE_TEMPLATE     = ePsiEJEtRXnDNaFGpywBX9vzeNQP4vUb
# ~~


# mbed SDK
# ----------------------------------
# BLE requires 92, otherwise 112
#
MBED_SDK_RELEASE        = 92


# Arduino.ORG
# ----------------------------------
#
ARDUINO_ORG_RELEASE     = 1.7.8


# Arduino.CC or Genuino with Boards Manager
# ----------------------------------
#
ARDUINO_CC_RELEASE      = 1.6.7

ARDUINO_AVR_RELEASE     = 1.6.9
AVR_GCC_RELEASE         = 4.8.1-arduino5
AVRDUDE_RELEASE         = 6.0.1-arduino5

# Boards for Arduino.CC 1.6.5 or Genuino
#
ADAFRUIT_AVR_RELEASE    = 1.4.5
ADAFRUIT_SAMD_RELEASE   = 1.0.6

ARDUINO_SAM_RELEASE     = 1.6.6
ARDUINO_SAMD_RELEASE    = 1.6.4
ARM_GCC_RELEASE         = 4.8.3-2014q1
BOSSAC_RELEASE          = 1.6.1-arduino
CMSIS_RELEASE           = 4.0.0-atmel
OPENOCD_RELEASE         = 0.9.0-arduino

CHIPKIT_RELEASE         = 1.1.0
PIC32_GCC_RELEASE       = 4.8.3-pic32gcc
PIC32_PROG_RELEASE      = v1.0.01-pic32gcc

COSA_AVR_RELEASE        = 1.2.0

DIGISTUMP_AVR_RELEASE   = 1.6.5
DIGISTUMP_OAK_RELEASE   = 0.9.3
DIGISTUMP_SAM_RELEASE   = 1.6.5

OAK_ESPTOOLS_RELEASE    = 0.9.1
OAK_MKSPIFFS_RELEASE    = 0.1.2
OAK_OAKCLI_RELEASE      = 0.9.3
OAK_EXTENSA_RELEASE     = 1.20.0-26-gb404fb9-2

ESP8266_RELEASE         = 2.0.0
ESPTOOLS_RELEASE        = 0.4.6
EXTENSA_RELEASE         = 1.20.0-26-gb404fb9-2

INTEL_EDISON_RELEASE    = 1.6.7+1.0
INTEL_GALILEO_RELEASE   = 1.6.7+1.0

LINKIT_ONE_RELEASE      = 1.1.21
LINKIT_DUO_RELEASE      = 0.1.6

LITTLEROBOTFRIENDS_AVR_RELEASE = 1.6.0

MOTEINO_AVR_RELEASE     = 1.0.0

PANSTAMP_AVR_RELEASE    = 1.5.4
PANSTAMP_MSP_RELEASE    = 1.0.6

REDBEARLAB_DUO_RELEASE  = 0.2.4
DUO_GCC_ARM_RELEASE     = 4.9-2015-q3
REDBEARLAB_AVR_RELEASE  = 1.0.2
REDBEARLAB_NRF_RELEASE  = 1.0.5
NRF_GCC_ARM_RELEASE     = 4.8.3-2014q1

RFDUINO_RELEASE         = 2.3.1

UDOO_NEO_RELEASE        = 1.6.5
UDOO_GCC_ARM_RELEASE    = 4.9-2014q4-20141203
UDOO_CLIENT_RELEASE     = 1.0
